<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>testfailingalert1</fullName>
        <description>testfailingalert1</description>
        <protected>false</protected>
        <recipients>
            <field>Email</field>
            <type>email</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/MarketingProductInquiryResponse</template>
    </alerts>
    <fieldUpdates>
        <fullName>Update1</fullName>
        <field>AssistantName</field>
        <name>Update1</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Null</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update2</fullName>
        <field>Department</field>
        <name>Update2</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Null</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update3</fullName>
        <field>Description</field>
        <name>Update3</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Null</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update4</fullName>
        <field>DoNotCall</field>
        <literalValue>1</literalValue>
        <name>Update4</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update5</fullName>
        <field>HasOptedOutOfEmail</field>
        <literalValue>0</literalValue>
        <name>Update5</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update6</fullName>
        <field>LeadSource</field>
        <name>Update6</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>NextValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update7</fullName>
        <field>MailingCity</field>
        <name>Update7</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Null</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update8</fullName>
        <field>OtherCity</field>
        <name>Update8</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Null</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Update9</fullName>
        <field>OtherCountry</field>
        <name>Update9</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Null</operation>
        <protected>false</protected>
    </fieldUpdates>
    <rules>
        <fullName>Workflow failing</fullName>
        <actions>
            <name>testfailingalert1</name>
            <type>Alert</type>
        </actions>
        <actions>
            <name>Update1</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Update2</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Update3</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Update4</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Update5</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Update6</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Update7</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Update8</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Update9</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Contact.AccountName</field>
            <operation>contains</operation>
            <value>test</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
</Workflow>
